woodpecker

diff --git a/.woodpecker/api.yml b/.woodpecker/api.yml
--- a/.woodpecker/api.yml
+++ b/.woodpecker/api.yml
@@ -2,19 +2,26 @@ steps:
   - name: build
     image: mcr.microsoft.com/dotnet/sdk:9.0
     when:
-      event: [push, manual]
+      event: [cron, manual]
       path: 'backend/*'
     commands:
-      - echo "API build and test"
-      - cd backend
-      - dotnet restore PhotoBank.Backend.sln
-      - dotnet build PhotoBank.Backend.sln --no-restore --configuration Release
-      - dotnet test PhotoBank.Backend.sln --no-build --configuration Release --filter "FullyQualifiedName~PhotoBank.UnitTests" || echo "API tests failed, ignoring"
+      - |	
+      if git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA | grep '^backend/'; then
+        echo "Изменения в backend — запускаем билд"
+        echo "API build and test"
+        cd backend
+        dotnet restore PhotoBank.Backend.sln
+        dotnet build PhotoBank.Backend.sln --no-restore --configuration Release
+        dotnet test PhotoBank.Backend.sln --no-build --configuration Release --filter "FullyQualifiedName~PhotoBank.UnitTests" || echo "API tests failed, ignoring"
+      else
+        echo "Нет изменений в backend — пропускаем билд"
+        exit 0
+      fi
 
   - name: publish
     image: docker:24.0.7-cli
     when:
-      event: [push, manual]
+      event: [cron, manual]
       path: 'backend/*'
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
@@ -24,10 +31,18 @@ steps:
       DOCKER_PASSWORD:
         from_secret: docker_password
     commands:
-      - echo "API docker build and push"
-      - docker version
-      - docker info
-      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
-      - docker build -t makhin/photobank-api:latest backend
-      - docker push makhin/photobank-api:latest
-      - docker logout
+      - |
+      if git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA | grep '^backend/'; then
+        echo "Изменения в backend — запускаем билд"
+        echo "API docker build and push"
+        docker version
+        docker info
+        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
+        docker build -t makhin/photobank-api:latest backend
+        docker push makhin/photobank-api:latest
+        docker logout
+      else
+        echo "Нет изменений в backend — пропускаем билд"
+        exit 0
+      fi
+
