woodpecker

diff --git a/.woodpecker/frontend.yml b/.woodpecker/frontend.yml
--- a/.woodpecker/frontend.yml
+++ b/.woodpecker/frontend.yml
@@ -8,12 +8,19 @@ steps:
       VITE_API_BASE_URL:
         from_secret: vite_api_base_url
     commands:
-      - echo "Frontend install, build and test"
-      - cd frontend
-      - corepack enable
-      - pnpm install --frozen-lockfile
-      - pnpm --filter @photobank/frontend build
-      - pnpm --filter @photobank/frontend test || echo "Frontend tests failed, ignoring"
+      - |
+        if git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA | grep '^frontend/packages/frontend'; then
+          echo "Изменения в frontned — запускаем билд"
+          echo "Frontend install, build and test"
+          cd frontend
+          corepack enable
+          pnpm install --frozen-lockfile
+          pnpm --filter @photobank/frontend build
+          pnpm --filter @photobank/frontend test || echo "Frontend tests failed, ignoring"
+        else
+          echo "Нет изменений в frontend — пропускаем билд"
+          exit 0
+        fi
 
   - name: publish
     image: docker:24.0.7-cli
@@ -30,10 +37,17 @@ steps:
       VITE_API_BASE_URL:
         from_secret: vite_api_base_url
     commands:
-      - echo "Frontend docker build and push"
-      - docker version
-      - docker info
-      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
-      - docker build -f frontend/Dockerfile.frontend -t makhin/photobank-frontend:latest --build-arg VITE_API_BASE_URL=$VITE_API_BASE_URL frontend
-      - docker push makhin/photobank-frontend:latest
-      - docker logout
+      - |
+        if git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA | grep '^frontend/packages/frontend'; then
+          echo "Изменения в frontned — запускаем билд"
+          echo "Frontend docker build and push"
+          docker version
+          docker info
+          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
+          docker build -f frontend/Dockerfile.frontend -t makhin/photobank-frontend:latest --build-arg VITE_API_BASE_URL=$VITE_API_BASE_URL frontend
+          docker push makhin/photobank-frontend:latest
+          docker logout
+        else
+          echo "Нет изменений в frontend — пропускаем билд"
+          exit 0
+        fi
diff --git a/.woodpecker/telegram-bot.yml b/.woodpecker/telegram-bot.yml
--- a/.woodpecker/telegram-bot.yml
+++ b/.woodpecker/telegram-bot.yml
@@ -8,12 +8,19 @@ steps:
       VITE_API_BASE_URL:
         from_secret: vite_api_base_url
     commands:
-      - echo "Telegram bot install, build and test"
-      - cd frontend
-      - corepack enable
-      - pnpm install --frozen-lockfile
-      - pnpm --filter @photobank/telegram-bot build
-      - pnpm --filter @photobank/telegram-bot test || echo "Telegram bot tests failed, ignoring"
+      - |
+        if git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA | grep '^frontend/packages/telegram-bot'; then
+          echo "Изменения в bot — запускаем билд"
+          echo "Telegram bot install, build and test"
+          cd frontend
+          corepack enable
+          pnpm install --frozen-lockfile
+          pnpm --filter @photobank/telegram-bot build
+          pnpm --filter @photobank/telegram-bot test || echo "Telegram bot tests failed, ignoring"
+        else
+          echo "Нет изменений в bot — пропускаем билд"
+          exit 0
+        fi
 
   - name: publish
     image: docker:24.0.7-cli
@@ -28,10 +35,17 @@ steps:
       DOCKER_PASSWORD:
         from_secret: docker_password
     commands:
-      - echo "Telegram bot docker build and push"
-      - docker version
-      - docker info
-      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
-      - docker build -f frontend/Dockerfile.bot -t makhin/photobank-bot:latest frontend
-      - docker push makhin/photobank-bot:latest
-      - docker logout
+      - |
+        if git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA | grep '^frontend/packages/telegram-bot'; then
+          echo "Изменения в bot — запускаем билд"
+          echo "Telegram bot docker build and push"
+          docker version
+          docker info
+          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
+          docker build -f frontend/Dockerfile.bot -t makhin/photobank-bot:latest frontend
+          docker push makhin/photobank-bot:latest
+          docker logout
+        else
+          echo "Нет изменений в bot — пропускаем билд"
+          exit 0
+        fi
